language: c

env:
  global:
    - SETARCH=

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang
      env: T=normal
    - os: linux
      dist: trusty
      compiler: gcc
      env: T=normal
    - os: linux
      dist: xenial
      compiler: clang
      env: T=normal
    - os: linux
      dist: xenial
      compiler: gcc
      env: T=normal
    - os: linux
      dist: trusty
      # https://packages.ubuntu.com/xenial/crossbuild-essential-armhf
      compiler: gcc
      arch: arm64
      env:
        - debugflags=-g0
        - SETARCH='setarch linux32 --verbose --32bit'
        - T=32bit
  allow_failures:
      dist: trusty
      # https://packages.ubuntu.com/xenial/crossbuild-essential-armhf
      compiler: gcc
      arch: arm64
      env:
        - debugflags=-g0
        - SETARCH='setarch linux32 --verbose --32bit'
        - T=32bit

sudo: required

before_install:
  - sudo apt-get update --quiet --assume-yes
  - sudo apt-get install splint --quiet --assume-yes
  - if [[ "$T" = "32bit" ]]; then sudo dpkg --add-architecture armhf; fi

before_script:
  - date # Debugging "Permission defined" failure on darwin like https://travis-ci.org/ruby/ruby/jobs/508683759
  - dpkg --print-architecture
  - dpkg --print-foreign-architectures
  - echo SETARCH=${SETARCH}
  - $SETARCH uname -a
  - $SETARCH uname -r

script:
  - ./autogen.sh
  - if [[ "$T" = "32bit" ]]; then $SETARCH ./configure -C; fi
  - if [[ "$T" = "normal" ]]; then ./configure --disable-shared; fi
  - make gen-code
  - make
  - make test
