language: c

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: gcc
      arch: arm32
      env: T=32bit

sudo: required

before_install:
  - sudo apt-get update --quiet --assume-yes
  - sudo apt-get install splint --quiet --assume-yes
  - if [[ "$T" = "32bit" ]]; then sudo apt-get install gcc-multilib --quiet --assume-yes; fi

before_script:
  - if [[ "$T" = "32bit" ]]; then export CLAFGS="-m32"; fi

script:
  - ./autogen.sh
  - ./configure --disable-shared
  - make gen-code
  - make
  - make test
