name: libgoldilocks pipeline
on: push
jobs:
  alpine:
    runs-on: [raspbian-private, ubuntu-latest]
    container: alpine:3
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
        apk add automake autoconf libtool make gcc g++
        autoreconf --install
        ./configure
        make all
        uname -m
        echo "arch=$(uname -m)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: libgoldilocks-${{ env.arch }}
        path: src/.libs/libgoldilocks.a
  build:
    runs-on: [macos-11, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
        autoreconf --install
        ./configure
        make all
        echo "arch=$(uname -m)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        name: libgoldilocks-${{ env.arch }}
        path: src/.libs/libgoldilocks.a
  relese:
    runs-on: ubuntu-latest
    needs: [alpine, build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - name: Zip
      run: zip -r -j libgoldilocks build/lib
    - name: Bump version
      id: version_bump
      uses: anothrNick/github-tag-action@1.13.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "master"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_bump.outputs.tag }}
        release_name: Release libgoldilocks ${{ steps.version_bump.outputs.tag }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: libgoldilocks.zip
        asset_name: libgoldilocks.zip
        asset_content_type: application/zip
