name: libgoldilocks pipeline
on: push
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Tag
      run: echo "branch=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Bump version
      id: version_bump
      uses: anothrNick/github-tag-action@1.13.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: ${{ env.branch }}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_bump.outputs.tag }}
        release_name: Release libgoldilocks ${{ steps.version_bump.outputs.tag }}
        draft: false
        prerelease: false
    - name: Release URL
      run: echo ${{ steps.create_release.outputs.upload_url }} > release.url
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release.url    
  alpine:
    runs-on: ubuntu-latest
    needs: release
    container: alpine:3
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Prepare
      uses: actions/download-artifact@v2
      with:
        name: release
        path: release.url
    - name: Build
      run: |
        apk add automake autoconf libtool make gcc g++
        autoreconf --install && ./configure && make all
        echo "arch=$(uname -m)" >> $GITHUB_ENV
        echo "url=$(cat release.url)" >> $GITHUB_ENV
        zip -r -j libgoldilocks-${{ env.RUNNER_OS}}-${{ env.arh}} src/.libs
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.url }}
        asset_path: libgoldilocks-${{ env.RUNNER_OS }}-${{ env.arch }}.zip
        asset_name: libgoldilocks-${{ env.RUNNER_OS }}-${{ env.arch }}.zip
        asset_content_type: application/zip
  build:
    runs-on: macos-private
    needs: release
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
        brew install automake libtool
        autoreconf --install && ./configure && make all
        echo "arch=$(uname -m)" >> $GITHUB_ENV
        echo "url=$(cat release.url)" >> $GITHUB_ENV
        zip -r -j libgoldilocks-${{ env.RUNNER_OS}}-${{ env.arh}} src/.libs
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ env.url }}
        asset_path: libgoldilocks-${{env.RUNNER_OS}}-${{env.arch}}.zip
        asset_name: libgoldilocks-${{env.RUNNER_OS}}-${{env.arch}}.zip
        asset_content_type: application/zip
