name: libgoldilocks pipeline
on: push
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, raspbian-private,]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
        docker build . -t libgoldilocks:${{matrix.platform}}
        docker create -it --name dummy libgoldilocks:ubuntu-latest bash
        docker cp dummy:/usr/local/bin/libgoldilocks.a .
        docker rm -f dummy
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: libgoldilocks-${{matrix.platform}}
        path: libgoldilocks.a
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download Linux artifact
      uses: actions/download-artifact@v2
      with:
        name: libgoldilocks-ubuntu-latest
        path: libgoldilocks-ubuntu-latest
    - name: Download RPi artifact
      uses: actions/download-artifact@v2
      with:
        name: libgoldilocks-raspbian-latest
        path: libgoldilocks-raspbian-latest
    - name: Create zip
      run: |
        zip -r libgoldilocks libgoldilocks-*
    - name: Fetch tag
      run: |
        echo "branch=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: Bump version
      id: version_bump
      uses: anothrNick/github-tag-action@1.13.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: ${{ env.branch }}
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version_bump.outputs.tag }}
        release_name: Release libgoldilocks ${{ steps.version_bump.outputs.tag }}
        draft: false
        prerelease: false
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: libgoldilocks.zip
        asset_name: libgoldilocks.zip
        asset_content_type: application/zip
