name: libgoldilocks build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
        autoreconf --install
        ./configure
        make lib
    - name: Test
      run: make test
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: libgoldilocks
        path: build/lib/*.*
